const country = 1;
let continent = 2;
const population = 3;
console.log(country);
console.log(continent);
console.log(population);
let IsIsland = true;
let language = "english";
console.log(typeof country);
console.log(typeof IsIsland);
console.log(typeof population);
console.log(typeof language);
continent = 3;
